### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by bounteous17** [akhil110/expensewatch#2]
Fix it creating the file _environment.ts_ and folder _environments_ inside _src_:
**vim src/environments/environment.ts**

// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

export const environment = {
  production: false
};

**Comment by naimjeem** [comment]
@bounteous thanks, now it works
