### ISSUE TITLE
Missing tsconfig.json

### ISSUE THREAD

**Issue by oscarlagatta** [akhil110/expensewatch#3]
Hi Akhilesh Srivastava, in file tsconfig.app.json  and tsconfig.spec.json there are references to a tsconfig.json that is not part of the repository, how this file looks like? I run the tests and receive errors of this missing file.

λ npm test

> expensewatch@0.0.0 test D:\sandbox\angular\testing\expensewatch
> jest

 FAIL  src/app/modules/expense/expense.service.spec.ts
  ● Test suite failed to run

    error TS5058: The specified path does not exist: 'D:/sandbox/angular/tsconfig.json'.

{
  **_"extends": "../../tsconfig.json",_**
  "compilerOptions": {
    "outDir": "../../out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}

**Comment by akhil110** [comment]
I have committed tsconfig.json

**Comment by oscarlagatta** [comment]
Thank you @akhil110
